// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication27.Data;

#nullable disable

namespace WebApplication27.Migrations
{
    [DbContext(typeof(WebApplication27Context))]
    [Migration("20230114182643_Colectie")]
    partial class Colectie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication27.Models.Colectie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeleColectiilor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Colectie");
                });

            modelBuilder.Entity("WebApplication27.Models.Institutie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Bilet")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("ColectieID")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ColectieID");

                    b.ToTable("Institutie");
                });

            modelBuilder.Entity("WebApplication27.Models.Institutie", b =>
                {
                    b.HasOne("WebApplication27.Models.Colectie", "Colectie")
                        .WithMany("Institutii")
                        .HasForeignKey("ColectieID");

                    b.Navigation("Colectie");
                });

            modelBuilder.Entity("WebApplication27.Models.Colectie", b =>
                {
                    b.Navigation("Institutii");
                });
#pragma warning restore 612, 618
        }
    }
}
